### ISSUE TITLE
Usage Instructions

### ISSUE THREAD

**Issue by hetunandu** [dalejmooney/laravel-google-datastore#2]
Hey, I am interested in this package and was wondering how to use it. Can you provide some helpful readme?

**Comment by dalejmooney** [comment]
Hello, This package is still currently under development. I can see its getting attention, so I can continue to develop it.

**Comment by hetunandu** [comment]
That's great. I don't know a lot about creating a laravel package but I would love to help you out :)

**Comment by wapnen** [comment]
hello? ive been watching this package for a while now.. any update?
